export const FETCH_POKEMON = 'POKEMON__FETCH_POKEMON';
export const FETCH_ERR = 'POKEMON__FETCH_ERROR';
export const FETCH_SUCCESS = 'POKEMON__FETCH_SUCCESS';
export const FETCH_LOADING = 'POKEMON__FETCH_LOADING';
export const SET_SELECTED = 'SELECTED__SET_SELECTED';
export const CLEAR_SELECTED = 'SELECTED__CLEAR_SELECTED';
